name: Publish Docker image to Docker Hub

on: 
    push:
        branches:
            - "main"

jobs:
    build-and-deploy:
        name: Build and Push Docker image
        runs-on: ubuntu-latest # specify the build machine
        steps:
            -   
                name: Checkout
                uses: actions/checkout@v4
                
            -   
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                  username: simon31fu
                  password: dckr_pat_L_3ftJCjjTCkpMlPoQXEwIEW6Gk
                  
            -   
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
                
            -   
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: simon31fu/fin488_project_1:latest
