name: Build and Push to Docker Hub

on:
  schedule:
    - cron: '27 1 * * *'
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: simon31fu
        password: dckr_pat_L_3ftJCjjTCkpMlPoQXEwIEW6Gk

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: risktoollib/app-shiny-stocks:latest
